// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18YDqj3Jwhe-EXwMXN5_QpT5E2xnfEqI',
    appId: '1:14117639892:web:11c09aad3c30986c980d41',
    messagingSenderId: '14117639892',
    projectId: 'chatapp-ce2b1',
    authDomain: 'chatapp-ce2b1.firebaseapp.com',
    storageBucket: 'chatapp-ce2b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_74ZKkUmCF3mfsqXdc7NBNGQhG106RI',
    appId: '1:14117639892:android:31812a0fdeeeb814980d41',
    messagingSenderId: '14117639892',
    projectId: 'chatapp-ce2b1',
    storageBucket: 'chatapp-ce2b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqGQ8aBsun5uE8PtmtR6qgfCFGHpGgJs',
    appId: '1:14117639892:ios:7dc621d032b09615980d41',
    messagingSenderId: '14117639892',
    projectId: 'chatapp-ce2b1',
    storageBucket: 'chatapp-ce2b1.appspot.com',
    iosBundleId: 'com.example.chatApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRqGQ8aBsun5uE8PtmtR6qgfCFGHpGgJs',
    appId: '1:14117639892:ios:14bbb26da83080af980d41',
    messagingSenderId: '14117639892',
    projectId: 'chatapp-ce2b1',
    storageBucket: 'chatapp-ce2b1.appspot.com',
    iosBundleId: 'com.example.chatApk.RunnerTests',
  );
}
